### ISSUE TITLE
Support  full window for ios

### ISSUE THREAD

**Issue by paladox** [hartman/videojs-ogvjs#23]
Hi please could you support  full window   for iOS, and if a user isen't using iOS use full screen api please.

Please see https://github.com/videojs/video.js/issues/3643#issuecomment-249616124

**Comment by paladox** [comment]
Thankyou

**Comment by hartman** [comment]
Note that this doesn't fix all issues, since it seems that the`<canvas>` is not being scaled up. Will have to check that with brion.

**Comment by paladox** [comment]
Oh ok

**Comment by hartman** [comment]
The remaining issue is possibly related to: brion/ogv.js#416

**Comment by paladox** [comment]
This fixes iOS, but we should support fullscreen api for Internet Explorer, Microsoft Edge and so on which do support this api.

Maybe we should do an usage agent detection or os detection?

**Comment by hartman** [comment]
If something does not support the fullscreen api, only THEN this check is called, and then this will always result in full window mode as far as I know, be it iOS or IE 10.

**Comment by paladox** [comment]
Oh but internet 11 supports full screen api support whereas Microsoft edge is working but that uses the the unprefixed full screen api whereas internet explorer uses the prefixed one.

See https://msdn.microsoft.com/en-us/library/dn265028%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by hartman** [comment]
@paladox yes I know. What's your point? What have you tested and confirmed not to be working ? I can't go blindly fixing things that may or may not be broken.

**Comment by paladox** [comment]
Well internet explorer only shows full screen but the task bar shows which means it isent full screen and is like iOS.

**Comment by hartman** [comment]
If that is a version of IE that supports a form of the fullscreen api, then it is likely a bug in https://github.com/videojs/video.js/blob/master/src/js/fullscreen-api.js, if that is a version of IE that does not support a form of the fullscreen api, then it is intentional.

You need to be much clearer in your descriptions of problems and situations tested paladox.. If we have to ping pong questions 6 times before we can get to an answer, then that easily adds up to over 30 minutes of my time wasted on opening pages, reading, questions and giving answers. In the mean time, i still don't know which specific version of IE is giving you a problem.

**Comment by paladox** [comment]
But I said here https://github.com/hartman/videojs-ogvjs/issues/23#issuecomment-252604424 what version of ie I'm using.

I'm using internet explorer 11 so this looks like a bug because it happends on the videojs website

**Comment by paladox** [comment]
Oh sorry to have waste your time. It's working again.

Seems to be related to a fix they did in windows 10 build 14342 which fixed edge and fixed site compatibility in ie.
